name: build-test-publish-docker
run-name: "Build, test, publish Docker images (branch ${{ github.ref_name }} on ${{ github.event_name }}/${{ github.event.action }} by ${{ github.actor }})"

# This workflow runs the build, test and publish steps for the
# Keyman build Docker images.
# It is triggered by a schedule and repository_dispatch event.

on:
  schedule:
    #run every Fri, 3 pm UTC
    - cron: '0 15 * * 5' #

  repository_dispatch:
    types: ['build-test-publish-docker:*']

env:
  # Use GitHub registry, if empty
  REGISTRY: ghcr.io
  USERNAME: "${{ github.actor }}"
  PASSWORD: "${{ github.token }}"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          if [ -n "${{ env.USERNAME }}" ]; then
            resources/docker-images/build.sh build: --registry ${{ env.REGISTRY }}
          else
            echo ${{ env.PASSWORD }} | resources/docker-images/build.sh build: --registry ${{ env.REGISTRY }} --username ${{ env.USERNAME }}
          fi


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Docker images
        run: |
          if [ -n "${{ env.USERNAME }}" ]; then
            resources/docker-images/build.sh test: --registry ${{ env.REGISTRY }}
          else
            echo ${{ env.PASSWORD }} | resources/docker-images/build.sh test: --registry ${{ env.REGISTRY }} --username ${{ env.USERNAME }}
          fi


  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Docker images
        run: |
          if [ -n "${{ env.USERNAME }}" ]; then
            resources/docker-images/build.sh publish: --registry ${{ env.REGISTRY }}
          else
            echo ${{ env.PASSWORD }} | resources/docker-images/build.sh publish: --registry ${{ env.REGISTRY }} --username ${{ env.USERNAME }}
          fi

